### ISSUE TITLE
'Deliver' stage fails

### ISSUE THREAD

**Issue by foger** [jenkins-docs/simple-python-pyinstaller-app#38]
The last stage in [example](https://jenkins.io/doc/tutorials/build-a-python-app-with-pyinstaller/) (Deliver) fails with error in Blue Ocean:

```
docker inspect -f . cdrx/pyinstaller-linux:python2
— Shell Script
<1s
+ docker inspect -f . cdrx/pyinstaller-linux:python2

.

Failed to run top 'b3a5844071e726298abc592422130a73bdf257e2174e0ef27cf4d6c891df91b6'. Error: Error response from daemon: Container b3a5844071e726298abc592422130a73bdf257e2174e0ef27cf4d6c891df91b6 is not running
```

(Exited with exit code 1)

Failed pyinstaller container logs inside of the Jenkins container:

```
bash-4.4$ docker logs b3a5844071e7
groups: cannot find name for group ID 1000
bash: /root/.bashrc: Permission denied
```

I've tried to add `args '-u root --privileged'` or `args '-u root:root'` into Jenkinsfile and gets another error in Blue Ocean: `pyinstaller not found.`

**Comment by foger** [comment]
My mistake, sorry.

**Comment by carterfieldslabs** [comment]
> My mistake, sorry.

I have the same issue. What was the fix?

**Comment by stsmuniz** [comment]
> My mistake, sorry.

Qual era o erro?
