### ISSUE TITLE
ValueError: script '/src/add2vals.py' not found

### ISSUE THREAD

**Issue by Qooooo** [jenkins-docs/simple-python-pyinstaller-app#48]
I was following [this](https://www.jenkins.io/doc/tutorials/build-a-python-app-with-pyinstaller/#add-a-final-deliver-stage-to-your-pipeline) tutorial and got stuck at the step of adding a 'Deliver" stage.

Error:
![image](https://user-images.githubusercontent.com/3146048/95804452-48c17d80-0d35-11eb-921c-cfd0e2200fca.png)

Any idea how to resolve this?

**Comment by AdeneXu** [comment]
I have the same issue.Have you solved it？

**Comment by AdeneXu** [comment]
I've solved it.
You need to check the volume path that should be a place of saving the jenkins data. 
![image](https://user-images.githubusercontent.com/28861746/101130035-b0ad8980-363d-11eb-8a10-b46dce969ef1.png)
