### ISSUE TITLE
Jenkins Pipeline Process Stops at the Test Stage

### ISSUE THREAD

**Issue by andisugandi** [jenkins-docs/simple-python-pyinstaller-app#79]
Hi @olblak ,

The Jenkins pipeline process by using [the original](https://github.com/jenkins-docs/simple-python-pyinstaller-app/blob/master/jenkins/Jenkinsfile) and  the modified version from [the User Handbook](https://www.jenkins.io/doc/tutorials/build-a-python-app-with-pyinstaller/#add-a-final-deliver-stage-to-your-pipeline) will be stop at the Test stage:

```
+ docker inspect -f . qnib/pytest
.
```

Please see screenshot and the pipeline `log.txt` file:

<img width="1512" alt="Screenshot 2024-01-02 at 18 58 27" src="https://github.com/jenkins-docs/simple-python-pyinstaller-app/assets/2184391/d0fef37d-07c7-415b-94ad-114d71abb989">

[log.txt](https://github.com/jenkins-docs/simple-python-pyinstaller-app/files/13809674/log.txt)

It is using Jenkins version `2.438` with `blueocean` and `docker-workflow` plugin enabled (following [the official Jenkins documentation](https://www.jenkins.io/doc/tutorials/build-a-python-app-with-pyinstaller/#run-jenkins-in-docker)).

What do you suggest?

Thank you in advance.

**Comment by gounthar** [comment]
Hello @andisugandi ,

Could you please give a try at this new version of the tutorial?
https://deploy-preview-6964--jenkins-io-site-pr.netlify.app/doc/tutorials/build-a-python-app-with-pyinstaller/

**Comment by MarkEWaite** [comment]
Closing after no response for months.
